version: "3.8"

services: 
    base-vuln:
        build: ./base-vuln/.
        volumes: 
            - ./base-vuln:/usr/src/app
        environment: 
            - REDIS=redis_db
        ports: 
            - "8000:8000"
    
    # xxe:
    #     build: ./xxe/.
    #     volumes: 
    #         - ./xxe/app:/app
    #     environment: 
    #         - DEBUG=1
    #     ports: 
    #         - "9000:9000"