version: "3.8"

services: 
    xss1:
        build: ./xss
        # volumes: 
        #     - ./xss:/usr/src/app
        environment: 
            - REDIS=redis_db
        ports: 
            - "40000:8000"
    
    redis_db:
        image: redis:6.0.8-alpine